### ISSUE TITLE
Sphinx build failure

### ISSUE THREAD

**Issue by bregnery** [cms-gem-daq-project/gembuild#3]
## Brief summary of issue

When doing `make pip` in `gem-plotting-tools` the sphinx build fails. 

```bash
make pip
PythonModules=["gempython.gemplotting", "gempython.gemplotting.utils", "gempython.gemplotting.fitting", "gempython.gemplotting.macros", "gempython.gemplotting.mapping" ]
Using BUILD_HOME=/data/bigdisk/users/bregnery
OS Detected: centos7
BUILD_VERSION 0.0.1.45.dev1
PREREL_VERSION -dev1.dev45
mkdir -p pkg/gempython/gemplotting
python /usr/bin/sphinx-build -b man -d /data/bigdisk/users/bregnery/gem-plotting-tools/doc/_build/doctrees   /data/bigdisk/users/bregnery/gem-plotting-tools/doc /data/bigdisk/users/bregnery/gem-plotting-tools/doc/_build/man
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/afs/cern.ch/user/b/bregnery/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/afs/cern.ch/user/b/bregnery/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/afs/cern.ch/user/b/bregnery/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/afs/cern.ch/user/b/bregnery/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 662, in _build_master
  File "/afs/cern.ch/user/b/bregnery/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 675, in _build_from_requirements
  File "/afs/cern.ch/user/b/bregnery/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'Sphinx==1.1.3' distribution was not found and is required by the application
make: *** [man] Error 1
```

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

I expected it to build.

## Current Behavior

It did not build.

## Possible Solution (for bugs)

In `mfSphinx.mk` there is a line which calls `python sphinx-build` 

https://github.com/cms-gem-daq-project/gembuild/blob/a0c94eca89363574014d1d7e6cbe310474b0ffdc/mfSphinx.mk#L7-L8

The commented line is what is in my version and the proper solution which is not the hacked solution is:

```python
python -m sphinx
```

With this change `make pip` succeeds.

## Your Environment

* Version used: `fbc0252`
* Shell used: `bash`

**Comment by jsturdy** [comment]
Seems initial problem was local environment based (unexpected `python` interpreter used), however, *definitely* the "temporary hack" needs to be removed, and *probably* the proposed solution should be implemented, unless there are things that break when using this invocation.
